/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/fontes': typeof FontesRoute
  '/newsletter': typeof NewsletterRoute
  '/noticias': typeof NoticiasRoute
  '/podcast': typeof PodcastRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/fontes': typeof FontesRoute
  '/newsletter': typeof NewsletterRoute
  '/noticias': typeof NoticiasRoute
  '/podcast': typeof PodcastRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/fontes': typeof FontesRoute
  '/newsletter': typeof NewsletterRoute
  '/noticias': typeof NoticiasRoute
  '/podcast': typeof PodcastRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/educacao'
    | '/fontes'
    | '/newsletter'
    | '/noticias'
    | '/podcast'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/educacao'
    | '/fontes'
    | '/newsletter'
    | '/noticias'
    | '/podcast'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/educacao'
    | '/fontes'
    | '/newsletter'
    | '/noticias'
    | '/podcast'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducacaoRoute: typeof EducacaoRoute
  FontesRoute: typeof FontesRoute
  NewsletterRoute: typeof NewsletterRoute
  NoticiasRoute: typeof NoticiasRoute
  PodcastRoute: typeof PodcastRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducacaoRoute: EducacaoRoute,
  FontesRoute: FontesRoute,
  NewsletterRoute: NewsletterRoute,
  NoticiasRoute: NoticiasRoute,
  PodcastRoute: PodcastRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
